apiVersion: v1
kind: Service
metadata:
  name: spa-mongodb
  namespace: spa-build-pipeline-1-prod
  labels:
    name: mongodb
spec:
  ports:
  - port: 27017
    targetPort: 27017
  clusterIP: None
  selector:
    name: mongodb
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb-stateful-set
  namespace: spa-build-pipeline-1-prod
spec:
  serviceName: spa-mongodb
  replicas: 1
  selector:
    matchLabels:
      name: mongodb
  template:
    metadata:
      labels:
        name: mongodb 
    spec:
      containers:
      - name: mongodb-standalone
        #image: pkdone/mongo-ent:3.4
        image: mongo:latest
        ports:
          - containerPort: 27017
      nodeSelector:
        kubernetes.io/hostname: mongodb-node