apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2020-12-08T15:45:14Z"
  labels:
    app.kubernetes.io/instance: spa-rmq
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: rabbitmq
    helm.sh/chart: rabbitmq-8.4.1
  name: spa-rmq
  namespace: spa-build-pipeline-1-prod
  resourceVersion: "35709598"
  selfLink: /api/v1/namespaces/spa-build-pipeline-1-prod/services/inc-rabbitmq
  uid: dcc694f9-f185-4abb-97a1-a8efe5469577
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: amqp
    nodePort: 31732
    port: 5672
    protocol: TCP
    targetPort: amqp
  - name: epmd
    nodePort: 31680
    port: 4369
    protocol: TCP
    targetPort: epmd
  - name: dist
    nodePort: 32371
    port: 25672
    protocol: TCP
    targetPort: dist
  - name: http-stats
    nodePort: 31748
    port: 15672
    protocol: TCP
    targetPort: stats
  selector:
    app.kubernetes.io/instance: spa-rmq
    app.kubernetes.io/name: rabbitmq
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}